-- 코드를 입력하세요
SELECT
    P.PRODUCT_ID, PRODUCT_NAME, (PRICE * SUM(AMOUNT)) AS TOTAL_SALES
FROM
    FOOD_PRODUCT AS P
    INNER JOIN FOOD_ORDER AS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE
    YEAR(PRODUCE_DATE) = 2022 AND
    MONTH(PRODUCE_DATE) = 5
GROUP BY
    P.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    P.PRODUCT_ID ASC
;